In [6]:
import numpy as np
arr = np.array([
                [1,2,3],
                [3,4,5]
               ])
arr.ndim

2

In [2]:
arr.shape

(2, 3)

In [4]:
arr.dtype

dtype('int32')

In [5]:
arr.size

6

In [11]:
barr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
barr[0,0] # row column index

1

In [13]:
barr[0,]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
barr[0, 1:6:2] ## Row : startIndex : endIndex : step

array([2, 4, 6])

In [24]:
Drr = np.array([ 
    [
        [1,2],[8,9]
    ],
    [
        [10,20],[28,29]
    ]
])
Drr

array([[[ 1,  2],
        [ 8,  9]],

       [[10, 20],
        [28, 29]]])

In [35]:
Drr[0:1:]

array([[[1, 2],
        [8, 9]]])

In [36]:
Drr.min()

1

In [37]:
Drr.max()

29

In [46]:
Drr.sum(axis=1)

array([[ 9, 11],
       [38, 49]])

In [42]:
print(np.linspace(1,3,4))

[1.         1.66666667 2.33333333 3.        ]


In [47]:
arange = np.arange(6)
print(arange)

[0 1 2 3 4 5]


In [48]:
oneDarray = np.array([[1,2,3,4,5],
                    [2,3,4,5,6],
                    [29,34,45,65,67]])
print(oneDarray)

[[ 1  2  3  4  5]
 [ 2  3  4  5  6]
 [29 34 45 65 67]]


In [57]:
# np.zeros(5)
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [56]:
# np.ones(5)
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [68]:
np.empty([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
np.arange(1,10,4)

array([1, 5, 9])

In [71]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [73]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [76]:
arr = np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [78]:
OneArr = np.array([1,2,3,5,6])
TwoArr = np.array([10,20,30,50,60])
np.concatenate((OneArr , TwoArr))

array([ 1,  2,  3,  5,  6, 10, 20, 30, 50, 60])

In [83]:
third = np.array([10,34,45,0])
np.concatenate((OneArr, TwoArr, third))

array([ 1,  2,  3,  5,  6, 10, 20, 30, 50, 60, 10, 34, 45,  0])

In [84]:
array_of_2D = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 13],
                           [4, 5, 6, 7]]])

print(array_of_2D.ndim, array_of_2D.size, array_of_2D.shape)

3 24 (3, 2, 4)


In [91]:
# Row -> then inner Row -> Column Number
array_of_2D[1][0][3]

3

In [93]:
arra = np.arange(6)
reShape = arra.reshape(3,2)

print(reShape)

print(np.reshape(arra , newshape=(1, 6) , order='C'))

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3 4 5]]


In [105]:
data = np.array([1,2,3,4,5])
data[-2:]

array([4, 5])

In [106]:
arr = np.array([
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ])

print(arr[arr > 5])

[ 6  7  8  9 10 11 12]


In [107]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [113]:
arr[(arr > 5) & (arr < 10)]

array([6, 7, 8, 9])

In [114]:
arr[(arr > 5) | (arr < 10)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [121]:
list_of_coordinates = list(zip([0,1,2,3,4,4,0,0], [1,4,54,5,4,3,4,3]))

print(list_of_coordinates)

[(0, 1), (1, 4), (2, 54), (3, 5), (4, 4), (4, 3), (0, 4), (0, 3)]


In [128]:
arrONE = np.array([[1, 1],
               [2, 2]])

arrTWO = np.array([[3, 3],
               [4, 4]])

np.vstack((arrONE , arrTWO))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [125]:
np.hstack((arrONE , arrTWO))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [134]:
copy = arrONE.copy()

data = np.array([1, 2])
ones = np.ones(2, dtype=int)

data, ones

(array([1, 2]), array([1, 1]))

In [140]:
b = np.array([[1, 1, 2], [2, 2, 2]])


print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.max())
print(b.min())
print(b.sum())

[3 3 4]
[4 6]
2
1
10
